### ISSUE TITLE
Insufficient funds

### ISSUE THREAD

**Issue by dajor** [racecrypto/racecoin#2]
**race-cli listaccounts**
{
  "": 1.00000000,
  "MN1": 1000.00000000,
  "MN2": 0.00000000
}
race-cli sendfrom MN1 RX9sTxYbFpC2s4RiJbpshNHTDkeXRMCKi7 0.01
error code: -4
error message:
**Insufficient funds.**

**Comment by racecrypto** [comment]
> DEPRECATED (use sendtoaddress). Sent an amount from an account to a race address.
