### ISSUE TITLE
Development - install.sh - Automatical Race MN installation

### ISSUE THREAD

**Issue by racecrypto** [racecrypto/racecoin#6]
Migration from PR #5 from @alebeta90

Here is a file for automatic deployment of the MN, what is pending is the implementation of sentinel within this script.

Here is a file for automatic deployment of the MN, what is pending is the implementation of sentinel within this script.
```
#!/bin/bash
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get install nano htop git -y
sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils software-properties-common libgmp3-dev -y
sudo apt-get install libboost-all-dev -y
sudo add-apt-repository ppa:bitcoin/bitcoin -y
sudo apt-get update -y
sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
sudo apt-get install libminiupnpc-dev -y
sudo mkdir $HOME/tempRACE
sudo chmod -R 777 $HOME/tempRACE
sudo git clone https://github.com/racecrypto/racecoin $HOME/tempRACE
cd $HOME/tempRACE
sudo chmod 777 autogen.sh
sudo ./autogen.sh
sudo ./configure
sudo chmod +x share/genbuild.sh
sudo make
sudo make install
cd $HOME
sudo mkdir $HOME/racecoin
sudo mkdir $HOME/.racecore
cp $HOME/tempRACE/src/raced $HOME/racecoin
cp $HOME/tempRACE/src/race-cli $HOME/racecoin
sudo chmod -R 777 $HOME/racecoin
sudo chmod -R 777 $HOME/.racecore
sudo apt-get install -y pwgen
EXIP=wget -qO- eth0.me
PASS=pwgen -1 20 -n
printf "rpcuser=user\nrpcpassword=$PASS\nrpcport=8801\ndaemon=1\nlisten=1\nserver=1\nmaxconnections=256\nrpcallowip=127.0.0.1\nexternalip=$EXIP:8800\n" > /$HOME/.racecore/race.conf
```

**Comment by madfungi** [comment]
I tried to this scrypt, but it's failed (Ubuntu 16.0.4).
So, I have made a new install.sh with another  Masternode Installation Guide. 
------------------------------------------------------------------------------------------------------------------

#!/bin/bash
sudo touch /var/swap.img

sudo chmod 600 /var/swap.img

sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=2000

mkswap /var/swap.img

sudo swapon /var/swap.img

sudo echo "/var/swap.img none swap sw 0 0" >> /etc/fstab

sudo apt-get update -y

sudo apt-get upgrade -y

sudo apt-get dist-upgrade -y

sudo apt-get install nano htop git -y

sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils software-properties-common libgmp3-dev -y

sudo apt-get install libboost-all-dev -y

sudo add-apt-repository ppa:bitcoin/bitcoin -y

sudo apt-get update -y

sudo apt-get install libdb4.8-dev libdb4.8++-dev -y

sudo apt-get install libminiupnpc-dev -y

sudo mkdir $HOME/tempRACE

sudo chmod -R 777 $HOME/tempRACE

sudo git clone https://github.com/racecrypto/racecoin $HOME/tempRACE

cd $HOME/tempRACE

sudo chmod 777 autogen.sh

sudo ./autogen.sh

sudo ./configure

sudo chmod +x share/genbuild.sh

sudo make

sudo make install

cd $HOME

sudo mkdir $HOME/racecoin

sudo mkdir $HOME/.racecore

cp $HOME/tempRACE/src/raced $HOME/racecoin

cp $HOME/tempRACE/src/race-cli $HOME/racecoin

sudo chmod -R 777 $HOME/racecoin

sudo chmod -R 777 $HOME/.racecore

sudo apt-get install -y pwgen

PASS="`"pwgen -1 20 -n"`"  --> # (" ") Delete double quote.

EXIP="`"curl ipinfo.io/ip"`" --> # (" ") Delete double quote.

printf "rpcuser=racerpc\nbind=$EXIP:8800\nexternalip=$EXIP:8800\ndaemon=1\nrpcpassword=$PASS\n" > /$HOME/.racecore/race.conf

cd /root/racecoin

./raced

sleep 10

masternodekey=$(./race-cli masternode genkey)

./race-cli stop

echo -e "masternode=1\nmasternodeprivkey=$masternodekey" >> /root/.racecore/race.conf

./raced -daemon

cd /root/.racecore

sudo apt-get install -y git python-virtualenv

sudo git clone https://github.com/racecrypto/sentinel.git

cd sentinel

mkdir database

export LC_ALL=C

sudo apt-get install -y virtualenv

virtualenv venv

venv/bin/pip install -r requirements.txt

echo "race_conf=/root/.racecore/race.conf" >> /root/.racecore/sentinel/sentinel.conf

crontab -l > tempcron

echo "* * * * * cd /root/.racecore/sentinel && ./venv/bin/python bin/sentinel.py 2>&1 >> sentinel-cron.log" >> tempcron

crontab tempcron

rm tempcron

echo "Masternode private key: $masternodekey"

echo "Welcome to the RACE world"
